services:
  oauth2-proxy:
    build:
      context: ..
      args:
        - VERSION=sandbox-development-testing
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_COOKIE_SECRET: "${COOKIE_SECRET}"
      OAUTH2_PROXY_COOKIE_DOMAINS: ".${DOMAIN}"
      OAUTH2_PROXY_WHITELIST_DOMAINS: "*.${DOMAIN}"
      OAUTH2_PROXY_COOKIE_SECURE: false
      OAUTH2_PROXY_COOKIE_SAMESITE: "lax"
      OAUTH2_PROXY_COOKIE_HTTPONLY: false
      OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST: true
      OAUTH2_PROXY_COOKIE_CSRF_EXPIRE: "5m"
      OAUTH2_PROXY_REVERSE_PROXY: true
      OAUTH2_PROXY_SESSION_COOKIE_MINIMAL: true
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"

      # Provider settings
      OAUTH2_PROXY_PROVIDER: ${PROVIDER}
      OAUTH2_PROXY_OIDC_ISSUER_URL: ${ISSUER_URL}
      OAUTH2_PROXY_REDIRECT_URL: ${REDIRECT_URL}
      OAUTH2_PROXY_CLIENT_ID: ${CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${CLIENT_SECRET}
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: "S256"

      # User id settings, not email but sub
      OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: true
      OAUTH2_PROXY_OIDC_EMAIL_CLAIM: sub
    expose:
      - "4180"

  whoami:
    image: traefik/whoami:latest
    expose:
      - "80"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - oauth2-proxy
      - whoami
